# Халиков Сардорбек Мирзохидович БФБО-03-24 

In [1]:
import numpy as np

In [4]:
a = np.array([1, 2, 3, 4, 5])   # 1D массив
a


array([1, 2, 3, 4, 5])

In [5]:
b = np.array([[1, 2, 3],        # 2D массив
              [4, 5, 6]])
b


array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
zeros_matrix = np.zeros((3, 4))   # нули
zeros_matrix


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
ones_vector = np.ones(5)   # единицы
ones_vector


array([1., 1., 1., 1., 1.])

In [8]:
arange_arr = np.arange(0, 20, 3)   # диапазон
arange_arr

array([ 0,  3,  6,  9, 12, 15, 18])

In [9]:
linspace_arr = np.linspace(0, 1, 5)   # равные шаги
linspace_arr


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [10]:
b, b.shape, b.ndim, b.size, b.dtype   # атрибуты


(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3),
 2,
 6,
 dtype('int64'))

In [11]:
elem1 = a[2]   # один элемент
elem1


np.int64(3)

In [12]:
slice1 = a[1:4]   # срез
slice1


array([2, 3, 4])

In [13]:
elem2 = b[1, 2]   # элемент
elem2


np.int64(6)

In [14]:
row = b[0, :]   # строка
row


array([1, 2, 3])

In [15]:
col = b[:, 1]   # столбец
col


array([2, 5])

In [24]:
x = np.array([10, 20, 30])
y = np.array([1, 2, 3])

sum_xy = x + y   # сложение
sum_xy





array([11, 22, 33])

In [21]:
mul_xy = x * y   # умножение
mul_xy



array([10, 40, 90])

In [23]:

div_xy = x / y   # деление
div_xy


array([10., 10., 10.])

In [25]:
matrix1 = np.array([[1, 2],
                    [3, 4]])

matrix2 = np.array([[5, 6],
                    [7, 8]])

matmul_res = matrix1 @ matrix2   # матр. умножение
matmul_res


array([[19, 22],
       [43, 50]])

In [26]:
elemwise_mul = matrix1 * matrix2   # поэлементно
elemwise_mul


array([[ 5, 12],
       [21, 32]])

In [27]:
stats_arr = np.array([2, 4, 6, 8, 10])

mean_val = stats_arr.mean()   # среднее
mean_val


np.float64(6.0)

In [28]:
std_val = stats_arr.std()   # std
std_val


np.float64(2.8284271247461903)

In [29]:
arr = np.array([5, 12, 3, 18, 7, 1])

mask = arr > 10   # маска
mask


array([False,  True, False,  True, False, False])

In [30]:
filtered = arr[arr > 10]   # фильтр
filtered


array([12, 18])

In [31]:
flat = np.arange(1, 13)       # 1..12
reshaped = flat.reshape(3, 4) # reshape
reshaped


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
# срез строки
reshaped[1]     # вторая строка


array([5, 6, 7, 8])

In [33]:
# срез столбца
reshaped[:, 2]  # третий столбец


array([ 3,  7, 11])

In [34]:
# подматрица
reshaped[0:2, 1:3]


array([[2, 3],
       [6, 7]])

In [35]:
# поэлементное сложение
added = reshaped + 10
added


array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22]])

In [36]:
# поэлементное умножение
multiplied = reshaped * 2
multiplied


array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [37]:
# среднее
reshaped.mean()


np.float64(6.5)

дз по math

In [39]:
import math 

In [44]:

# перевод градусов в радианы
angle_deg = 180
angle_rad = math.radians(angle_deg)
print("градус в", angle_rad, "радиан")

# перевод радиан в градусы
angle_rad2 = math.pi
angle_deg2 = math.degrees(angle_rad2)
print("радиан в", angle_deg2, "градус")



градус в 3.141592653589793 радиан
радиан в 180.0 градус
